### PR TITLE
Parallel Blob Uploading

### PR DESCRIPTION
**Pull request by thecolorblue**
Tested in mac osx/chrome. This could use a little more code cleanup, for example, how this handles the part number doesn't really make sense anymore. 

This does change how progress is handled and the bars do not make as much sense as they did before. Maybe there should be one per blob?

### CODE REVIEW

**Comment by thecolorblue** [comment]
The second change rearranges the methods on S3MultiUpload to use prototype (its more javascripty, and has slightly better performance).

**Comment by ienzam** [comment]
Great :+1: :+1: :+1: 

One feature request: a parameter to control the number of parallel uploads?

**Comment by thecolorblue** [comment]
That would be nice. I have only tested this on relatively small files (10
mb or less).
Should this number be passed in on initializing, or as a method?

Brad Davis
brad.bdavis1@gmail.com
(330)333-2723

**Comment by ienzam** [comment]
I think a method will be better with sensible default (like 4 parallel
upload?)

--Regards
Enzam

**Pull request merged**
